import { Exo_2 } from 'next/font/google';
import type { Metadata } from 'next';
import '@/src/app/styles/globals.scss';
import '@/src/app/styles/utils.scss';

const exo2 = Exo_2({
  subsets: ['cyrillic'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Smart Tekh',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='ru'
      className={`${exo2.className}`}
    >
      <body>{children}</body>
    </html>
  );
}
